apiVersion: v1
kind: Service
metadata:
  name: roadless-rule
  namespace: schmidtdse
  labels:
    app: roadless-rule
spec:
  type: ClusterIP
  selector:
    app: roadless-rule
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
